FROM node:18.16-alpine
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

ARG NODE_ENV=production

WORKDIR /cms/
COPY ./apps/cms/package.json ./
COPY ./yarn.lock ./
RUN yarn global add node-gyp
RUN yarn config set network-timeout 600000 -g && yarn install
ENV PATH /cms/node_modules/.bin:$PATH

WORKDIR /cms/app
COPY ./apps/cms .

RUN ["yarn", "build"]
EXPOSE 1337
CMD ["yarn", "start"]
