version: '3.1'

services:
  db:
    build: './postgresql'
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - ./volumes/database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - 127.0.0.1:8888:8080
